### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by daviszhen** [zenithdb/zenith#1073]
Following the compiling step, I get the error on the main branch:

error[E0658]: use of unstable library feature 'array_map'
   --> zenith_utils/src/pq_proto.rs:690:60
    |
690 |                 let iov = &mut [name, b"\0", value, b"\0"].map(IoSlice::new);
    |                                                            ^^^
    |
    = note: see issue #75243 <https://github.com/rust-lang/rust/issues/75243> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `zenith_utils`

Caused by:

**Comment by SomeoneToIgnore** [comment]
Looks like you use rather old `rustc` to build the project, `map` is stable since rust `1.55.0`, according to the [sources](https://doc.rust-lang.org/src/core/array/mod.rs.html#398):

> `#[stable(feature = "array_map", since = "1.55.0")]`

Currently we [guarantee](https://github.com/zenithdb/zenith/blob/main/.circleci/config.yml#L7) that the project builds with `1.56.1` and implicitly guarantee that it builds with the latest stable, `1.57.0` too.

Unfortunately, I don't think we're able to provide support for older rustc versions right now, so as a solution for this issue, please use `rustc` `1.56.1` or newer to build the project.
